### ISSUE TITLE
Version available on Packagist (for Composer) is not available on Github

### ISSUE THREAD

**Issue by the-line** [parcelpronl/magento2-module#15]
On Packagist (https://packagist.org/packages/parcelpro/shipment) there is a newer version available of this package. The version on Packagist is 2.14.0 that is not available here.

What are the differences between the two version?

**Comment by LucaScorpion** [comment]
Hi there! I think we must have missed something there. Looking at Packagist and  the tags in this repo now, it seems they are all synced up, do I'll close this issue. Feel free to reach out if you notice somthing is still off though!
